export const COMMON_TIMEZONES = [
  { value: 'America/New_York', label: 'Eastern Time (UTC-5/-4)', offset: -5 },
  { value: 'America/Chicago', label: 'Central Time (UTC-6/-5)', offset: -6 },
  { value: 'America/Denver', label: 'Mountain Time (UTC-7/-6)', offset: -7 },
  { value: 'America/Los_Angeles', label: 'Pacific Time (UTC-8/-7)', offset: -8 },
  { value: 'America/Phoenix', label: 'Arizona (UTC-7)', offset: -7 },
  { value: 'America/Anchorage', label: 'Alaska (UTC-9/-8)', offset: -9 },
  { value: 'Pacific/Honolulu', label: 'Hawaii (UTC-10)', offset: -10 },
  { value: 'America/Toronto', label: 'Toronto (UTC-5/-4)', offset: -5 },
  { value: 'America/Vancouver', label: 'Vancouver (UTC-8/-7)', offset: -8 },
  { value: 'America/Mexico_City', label: 'Mexico City (UTC-6/-5)', offset: -6 },
  { value: 'America/Sao_Paulo', label: 'São Paulo (UTC-3)', offset: -3 },
  { value: 'America/Argentina/Buenos_Aires', label: 'Buenos Aires (UTC-3)', offset: -3 },
  { value: 'America/Bogota', label: 'Bogotá (UTC-5)', offset: -5 },
  { value: 'America/Lima', label: 'Lima (UTC-5)', offset: -5 },
  { value: 'America/Santiago', label: 'Santiago (UTC-3/-4)', offset: -3 },
  { value: 'America/Caracas', label: 'Caracas (UTC-4)', offset: -4 },
  { value: 'America/Panama', label: 'Panama (UTC-5)', offset: -5 },
  { value: 'America/Costa_Rica', label: 'Costa Rica (UTC-6)', offset: -6 },
  { value: 'America/Barbados', label: 'Barbados (UTC-4)', offset: -4 },
  { value: 'Europe/London', label: 'London (UTC+0/+1)', offset: 0 },
  { value: 'Europe/Paris', label: 'Paris (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Berlin', label: 'Berlin (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Madrid', label: 'Madrid (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Rome', label: 'Rome (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Amsterdam', label: 'Amsterdam (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Brussels', label: 'Brussels (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Vienna', label: 'Vienna (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Zurich', label: 'Zurich (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Stockholm', label: 'Stockholm (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Copenhagen', label: 'Copenhagen (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Oslo', label: 'Oslo (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Helsinki', label: 'Helsinki (UTC+2/+3)', offset: 2 },
  { value: 'Europe/Warsaw', label: 'Warsaw (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Prague', label: 'Prague (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Budapest', label: 'Budapest (UTC+1/+2)', offset: 1 },
  { value: 'Europe/Athens', label: 'Athens (UTC+2/+3)', offset: 2 },
  { value: 'Europe/Istanbul', label: 'Istanbul (UTC+3)', offset: 3 },
  { value: 'Europe/Moscow', label: 'Moscow (UTC+3)', offset: 3 },
  { value: 'Europe/Dublin', label: 'Dublin (UTC+0/+1)', offset: 0 },
  { value: 'Europe/Lisbon', label: 'Lisbon (UTC+0/+1)', offset: 0 },
  { value: 'Africa/Cairo', label: 'Cairo (UTC+2)', offset: 2 },
  { value: 'Africa/Johannesburg', label: 'Johannesburg (UTC+2)', offset: 2 },
  { value: 'Africa/Lagos', label: 'Lagos (UTC+1)', offset: 1 },
  { value: 'Africa/Nairobi', label: 'Nairobi (UTC+3)', offset: 3 },
  { value: 'Asia/Dubai', label: 'Dubai (UTC+4)', offset: 4 },
  { value: 'Asia/Riyadh', label: 'Riyadh (UTC+3)', offset: 3 },
  { value: 'Asia/Tehran', label: 'Tehran (UTC+3:30/+4:30)', offset: 3.5 },
  { value: 'Asia/Karachi', label: 'Karachi (UTC+5)', offset: 5 },
  { value: 'Asia/Kolkata', label: 'India (UTC+5:30)', offset: 5.5 },
  { value: 'Asia/Dhaka', label: 'Dhaka (UTC+6)', offset: 6 },
  { value: 'Asia/Bangkok', label: 'Bangkok (UTC+7)', offset: 7 },
  { value: 'Asia/Singapore', label: 'Singapore (UTC+8)', offset: 8 },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong (UTC+8)', offset: 8 },
  { value: 'Asia/Shanghai', label: 'Shanghai (UTC+8)', offset: 8 },
  { value: 'Asia/Tokyo', label: 'Tokyo (UTC+9)', offset: 9 },
  { value: 'Asia/Seoul', label: 'Seoul (UTC+9)', offset: 9 },
  { value: 'Australia/Sydney', label: 'Sydney (UTC+10/+11)', offset: 10 },
  { value: 'Australia/Melbourne', label: 'Melbourne (UTC+10/+11)', offset: 10 },
  { value: 'Australia/Brisbane', label: 'Brisbane (UTC+10)', offset: 10 },
  { value: 'Australia/Perth', label: 'Perth (UTC+8)', offset: 8 },
  { value: 'Pacific/Auckland', label: 'Auckland (UTC+12/+13)', offset: 12 },
  { value: 'Pacific/Fiji', label: 'Fiji (UTC+12/+13)', offset: 12 },
  { value: 'UTC', label: 'UTC (UTC+0)', offset: 0 },
] as const;

export const DEFAULT_LAYOUT = 'month' as const;
export const DEFAULT_TIME_FORMAT = '12h' as const;
export const TIME_FORMATS = ['12h', '24h'] as const;
export const MIN_TOUCH_TARGET = 44; // pixels
